title: "Camden Yale Professional Portfolio" 
logo: "/docs/assets/DSC04728.jpeg"
description: "Software Engineer | Dual Degree Candidate"
theme: jekyll-theme-modernist

name: "Camden Yale"
email: "cyale@tulane.edu"
